### PR TITLE
Add lebara and info about airport

### PR DESCRIPTION
**Pull request by drubin**
Additional information about airport purchasing and the new requirement for Passport.

### CODE REVIEW

**Comment by marlonbernardes** [comment]
@drubin thanks a lot for submitting your PR! I'll merge it (and update the website) tomorrow, as I'm not at home right now!

**Comment by drubin** [comment]
I just noticed a typo Will fix tomorrow too.

**Comment by marlonbernardes** [comment]
👍  thanks once again!

**Comment by marlonbernardes** [comment]
@drubin I just deployed a new version of the guide, in less than 5 minutes your changes should be live :)

**Comment by drubin** [comment]
:+1: awesome guide looking forward go contributing more

**Pull request merged**
