### PR TITLE
Picking up permanent drivers license

### LINKED ISSUE #64: [en] Add permanent drivers license section
Need section on obtaining the permanent drivers license after receiving the temporary license.

### PR DESCRIPTION
**Pull request by gregdeane**
Closes #64

### CODE REVIEW

**Comment by gregdeane** [comment]
@marlonbernardes As always, feel free to clean up the text or present it in another way.

**Comment by marlonbernardes** [comment]
AwesoHey @gregdeane, thanks once again for your PR! Awesome! I'm merging it now, but I'll only update the website tomorrow!

**Comment by marlonbernardes** [comment]
Hey @gregdeane, I just published your changes to the website. Thanks once again!

**Comment by gregdeane** [comment]
Thanks a lot @marlonbernardes! Looks great. I noticed that I forgot one thing though. I'll fix it shortly.

**Pull request merged**
